"""add_suggestion_to_conversation

Revision ID: 86729507e0a1
Revises: i4d5e6f7a8b9
Create Date: 2026-07-06 03:10:55.160275

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '86729507e0a1'
down_revision: Union[str, None] = 'i4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('suggestion', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'suggestion')
    # ### end Alembic commands ###
